[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.141"
grep = "0.3.2"
walkdir = "2.5.0"
anyhow = "1.0.98"
ignore = "0.4.23"
regex = "1.11.1"
log = "0.4.27"
env_logger = "0.11.8"
pathdiff = "0.2.3"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.jsonc-parser]
version = "0.26"
features = ["serde"]

[dev-dependencies]
clippy = "0.0.302"
