export { default as eslintAstroConfig } from './astro';
export { default as eslintBaseConfig } from './base';
export { default as eslintElysiaConfig } from './elysia';
export { default as eslintFunctionalConfig } from './functional';
export { default as eslintPrettierConfig } from './prettier';
export { default as eslintReactConfig } from './react';
export { default as eslintTurboConfig } from './turbo';
export { default as eslintTypescriptConfig } from './typescript';
export { default as eslintNextConfig } from './next';
